In [2]:

# Data

company_detail_list = [
      {
          'name': 'Company 1',
          'domain': 'Retail',
          'country': 'United States'
      },
      {
          'name': 'Company 2',
          'domain': 'Technology',
          'country': 'United Kingdom'
      },
      {
          'name': 'Company 3',
          'domain': 'Healthcare',
          'country': 'United States'
      }
  ]

employee_detail_list = [
     {
          'name': 'EMP-0001',
          'first_name': 'John',
          'last_name': 'Doe',
          'full_name': 'John Doe',
          'company': 'Company 1',
          'nationality': 'Australia'
      },
      {
          'name': 'EMP-0002',
          'first_name': 'Tom',
          'last_name': 'Smith',
          'full_name': 'Tom Smith',
          'company': 'Company 2',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0003',
          'first_name': 'Andrew',
          'last_name': 'Sebastian',
          'full_name': 'Andrew Sebastian',
          'company': 'Company 3',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0005',
          'first_name': 'Ying Han',
          'last_name': 'Tan',
          'full_name': 'Ying Han Tan',
          'company': 'Company 1',
          'nationality': 'Australia'
      },
      {
          'name': 'EMP-0015',
          'first_name': 'Kenneth',
          'last_name': 'Ng',
          'full_name': 'Kenneth Ng',
          'company': 'Company 3',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0018',
          'first_name': 'Rubby',
          'last_name': 'Lee',
          'full_name': 'Rubby Lee',
          'company': 'Company 2',
          'nationality': 'Hong Kong'
      },
     {
          'name': 'EMP-0017',
          'first_name': 'Robert',
          'last_name': 'White',
          'full_name': 'Robert White',
          'company': 'Company 1',
          'nationality': 'United Kingdom'
      }
  ]

In [9]:
# Print the company details
print("Company Details:")
for company in company_detail_list:
    print(f"\tName: {company['name']}")
    print(f"\tDomain: {company['domain']}")
    print(f"\tCountry: {company['country']}")
    print("")

# Print the employee details with company name instead of company code
print("Employee Details:")
for employee in employee_detail_list:
    for company in company_detail_list:
        if employee["company"] == company["name"]:
            company_name = company["name"]
            break
    print(f"\tName: {employee['full_name']}")
    print(f"\tCompany: {company_name}")
    print(f"\tNationality: {employee['nationality']}")
    print("")

Company Details:
	Name: Company 1
	Domain: Retail
	Country: United States

	Name: Company 2
	Domain: Technology
	Country: United Kingdom

	Name: Company 3
	Domain: Healthcare
	Country: United States

Employee Details:
	Name: John Doe
	Company: Company 1
	Nationality: Australia

	Name: Tom Smith
	Company: Company 2
	Nationality: United States

	Name: Andrew Sebastian
	Company: Company 3
	Nationality: United States

	Name: Ying Han Tan
	Company: Company 1
	Nationality: Australia

	Name: Kenneth Ng
	Company: Company 3
	Nationality: United States

	Name: Rubby Lee
	Company: Company 2
	Nationality: Hong Kong

	Name: Robert White
	Company: Company 1
	Nationality: United Kingdom

In [ ]:
Task 1
Please get the list of all Companies and sort by Company Name in reverse order.

Expected result:

[{
    "name": "Company 3"
}, {
    "name": "Company 2"
}, {
    "name": "Company 1"
}]

In [10]:
# Sort the list of companies by name in descending order
sorted_companies = sorted(company_detail_list, key=lambda x: x['name'], reverse=True)

# Print the sorted companies
print(sorted_companies)

[{'name': 'Company 3', 'domain': 'Healthcare', 'country': 'United States'}, {'name': 'Company 2', 'domain': 'Technology', 'country': 'United Kingdom'}, {'name': 'Company 1', 'domain': 'Retail', 'country': 'United States'}]

In [ ]:
Soal 2
Please print all Domain value in every company (use print statement).

Expected return:

    Company 1: Retail (United States)
    Company 2: Technology (United Kingdom)
    Company 3: Healthcare (United States)

In [19]:
company_detail_list = [
    {
        'name': 'Company 1',
        'domain': 'Retail',
        'country': 'United States'
    },
    {
        'name': 'Company 2',
        'domain': 'Technology',
        'country': 'United Kingdom'
    },
    {
        'name': 'Company 3',
        'domain': 'Healthcare',
        'country': 'United States'
    }
]

for company in company_detail_list:
    print(f"{company['name']}: {company['domain']} ({company['country']})")

Company 1: Retail (United States)
Company 2: Technology (United Kingdom)
Company 3: Healthcare (United States)

In [ ]:
Task 3
List all Employees work By company domain.

Expected return:

{
    "Retail": [
         "John Doe",
         "Robert White",
         "Ying Han Tan"
     ],
    "Technology":[
          "Tom Smith",
          "Rubby Lee",
     ],
    "Healthcare": [
         "Kenneth Ng",
         "Andrew Sebastian"
     ],
}

In [26]:
# Create a mapping of domain to employees
domain_to_employees = {}

# Build the mapping
for company in company_detail_list:
    domain = company['domain']
    domain_to_employees[domain] = []

for employee in employee_detail_list:
    company_name = employee['company']
    full_name = employee['full_name']
    
    # Find the corresponding domain for the employee's company
    for company in company_detail_list:
        if company['name'] == company_name:
            domain_to_employees[company['domain']].append(full_name)

# Print the result
print(domain_to_employees)

{'Retail': ['John Doe', 'Ying Han Tan', 'Robert White'], 'Technology': ['Tom Smith', 'Rubby Lee'], 'Healthcare': ['Andrew Sebastian', 'Kenneth Ng']}

In [ ]:
Task 4
Create a function that return employees with it's company country.

Expected return:

[{
    "full_name": "John Doe",
    "company": "Company 1",
    "country": "United States"
}, {
    "full_name": "Tom Smith",
    "company": "Company 2",
    "country": "United Kingdom"
}, {
    "full_name": "Andrew Sebastian",
    "company": "Company 3",
    "country": "United Kingdom"
},  {
    "full_name": "Ying Han Tan",
    "company": "Company 1",
    "country": "United States"
},  {
    "full_name": "Kenneth Ng",
    "company": "Company 3",
    "country": "United States"
},  {
    "full_name": "Rubby Lee",
    "company": "Company 2",
    "country": "United Kingdom"
},   {
    "full_name": "Robert White",
    "company": "Company 1",
    "country": "United States"
},
    
]

In [31]:
def get_employees_with_company_country(employee_list, company_list):
    result = []
    
    # Create a mapping of company names to their countries
    company_country_map = {company['name']: company['country'] for company in company_list}
    
    # Build the result list
    for employee in employee_list:
        full_name = employee['full_name']
        company_name = employee['company']
        
        # Get the corresponding country from the mapping
        country = company_country_map.get(company_name, "Unknown")
        
        result.append({
            "full_name": full_name,
            "company": company_name,
            "country": country
        })
    
    return result

# Call the function and print the result
employees_with_country = get_employees_with_company_country(employee_detail_list, company_detail_list)
print(employees_with_country)

[{'full_name': 'John Doe', 'company': 'Company 1', 'country': 'United States'}, {'full_name': 'Tom Smith', 'company': 'Company 2', 'country': 'United Kingdom'}, {'full_name': 'Andrew Sebastian', 'company': 'Company 3', 'country': 'United States'}, {'full_name': 'Ying Han Tan', 'company': 'Company 1', 'country': 'United States'}, {'full_name': 'Kenneth Ng', 'company': 'Company 3', 'country': 'United States'}, {'full_name': 'Rubby Lee', 'company': 'Company 2', 'country': 'United Kingdom'}, {'full_name': 'Robert White', 'company': 'Company 1', 'country': 'United States'}]

In [ ]:
Task 5
Create a function that return companies with a number of employees nationality that are working in the company.

Expected return:

[{
    "company": "Company 1",
    "employee_nationality": {
        "Australia": 2,
        "Hong Kong": 1
    }
}, {
    "company": "Company 2",
    "employee_nationality": {
        "Hong Kong": 1,
        "United States": 1
    }
}, {
    "company": "Company 3",
    "employee_nationality": {
        "United States": 2
    }
}]

In [28]:
def get_companies_with_employee_nationality(employee_list, company_list):
    result = []
    
    # Create a mapping of company names to their employee nationalities
    company_nationality_map = {}
    
    # Populate the mapping
    for employee in employee_list:
        company_name = employee['company']
        nationality = employee['nationality']
        
        if company_name not in company_nationality_map:
            company_nationality_map[company_name] = {}
        
        if nationality not in company_nationality_map[company_name]:
            company_nationality_map[company_name][nationality] = 0
        
        company_nationality_map[company_name][nationality] += 1

    # Build the result list
    for company in company_list:
        company_name = company['name']
        employee_nationality = company_nationality_map.get(company_name, {})
        
        result.append({
            "company": company_name,
            "employee_nationality": employee_nationality
        })
    
    return result

# Call the function and print the result
companies_with_nationality = get_companies_with_employee_nationality(employee_detail_list, company_detail_list)
print(companies_with_nationality)

[{'company': 'Company 1', 'employee_nationality': {'Australia': 2, 'United Kingdom': 1}}, {'company': 'Company 2', 'employee_nationality': {'United States': 1, 'Hong Kong': 1}}, {'company': 'Company 3', 'employee_nationality': {'United States': 2}}]